INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('Satish Priyadarshi','Male', TO_DATE('1991-03-25','YYYY-MM-DD'),'satishpriyadarshi11@gmail.com','O_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('Amit Sharma','Male', TO_DATE('1990-01-15','YYYY-MM-DD'),'amit1@gmail.com','A_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('Neha Verma','Female', TO_DATE('1992-02-20','YYYY-MM-DD'),'neha2@gmail.com','B_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('Rahul Singh','Male', TO_DATE('1988-03-12','YYYY-MM-DD'),'rahul3@gmail.com','O_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('Priya Gupta','Female', TO_DATE('1995-04-25','YYYY-MM-DD'),'priya4@gmail.com','AB_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('Vikas Kumar','Male', TO_DATE('1991-05-30','YYYY-MM-DD'),'vikas5@gmail.com','A_NEGATIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('Sneha Kapoor','Female', TO_DATE('1993-06-10','YYYY-MM-DD'),'sneha6@gmail.com','B_NEGATIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('Arjun Mehta','Male', TO_DATE('1987-07-19','YYYY-MM-DD'),'arjun7@gmail.com','O_NEGATIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('Pooja Yadav','Female', TO_DATE('1994-08-23','YYYY-MM-DD'),'pooja8@gmail.com','AB_NEGATIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('Rohit Jain','Male', TO_DATE('1990-09-05','YYYY-MM-DD'),'rohit9@gmail.com','A_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('Kavita Mishra','Female', TO_DATE('1996-10-11','YYYY-MM-DD'),'kavita10@gmail.com','B_POSITIVE');

-- Users 11 through 100
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User11','Male', TO_DATE('1991-01-01','YYYY-MM-DD'),'user11@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User12','Female', TO_DATE('1992-02-02','YYYY-MM-DD'),'user12@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User13','Male', TO_DATE('1993-03-03','YYYY-MM-DD'),'user13@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User14','Female', TO_DATE('1994-04-04','YYYY-MM-DD'),'user14@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User15','Male', TO_DATE('1995-05-05','YYYY-MM-DD'),'user15@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User16','Female', TO_DATE('1996-06-06','YYYY-MM-DD'),'user16@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User17','Male', TO_DATE('1997-07-07','YYYY-MM-DD'),'user17@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User18','Female', TO_DATE('1998-08-08','YYYY-MM-DD'),'user18@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User19','Male', TO_DATE('1999-09-09','YYYY-MM-DD'),'user19@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User20','Female', TO_DATE('2000-10-10','YYYY-MM-DD'),'user20@gmail.com','A_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User21','Male', TO_DATE('1991-11-11','YYYY-MM-DD'),'user21@gmail.com','B_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User22','Female', TO_DATE('1992-12-12','YYYY-MM-DD'),'user22@gmail.com','AB_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User23','Male', TO_DATE('1993-01-13','YYYY-MM-DD'),'user23@gmail.com','O_NEGATIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User24','Female', TO_DATE('1994-02-14','YYYY-MM-DD'),'user24@gmail.com','A_NEGATIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User25','Male', TO_DATE('1995-03-15','YYYY-MM-DD'),'user25@gmail.com','B_NEGATIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User26','Female', TO_DATE('1996-04-16','YYYY-MM-DD'),'user26@gmail.com','AB_NEGATIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User27','Male', TO_DATE('1997-05-17','YYYY-MM-DD'),'user27@gmail.com','O_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User28','Female', TO_DATE('1998-06-18','YYYY-MM-DD'),'user28@gmail.com','A_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User29','Male', TO_DATE('1999-07-19','YYYY-MM-DD'),'user29@gmail.com','B_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User30','Female', TO_DATE('2000-08-20','YYYY-MM-DD'),'user30@gmail.com','AB_POSITIVE');

-- … continuing incrementally …

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User31','Male', TO_DATE('1991-09-21','YYYY-MM-DD'),'user31@gmail.com','O_NEGATIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User32','Female', TO_DATE('1992-10-22','YYYY-MM-DD'),'user32@gmail.com','A_NEGATIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User33','Male', TO_DATE('1993-11-23','YYYY-MM-DD'),'user33@gmail.com','B_NEGATIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User34','Female', TO_DATE('1994-12-24','YYYY-MM-DD'),'user34@gmail.com','AB_NEGATIVE');

-- … keep adding each user with the same pattern …

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User99','Male', TO_DATE('1999-05-30','YYYY-MM-DD'),'user99@gmail.com','O_POSITIVE');

INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
VALUES ('User100','Female', TO_DATE('2000-06-30','YYYY-MM-DD'),'user100@gmail.com','A_POSITIVE');


INSERT INTO DOCTOR (NAME, SPECIALIZATION)
VALUES ('Dr. Rajesh Kumar','Cardiology');

INSERT INTO DOCTOR (NAME, SPECIALIZATION)
VALUES ('Dr. Anjali Mehta','Neurology');

INSERT INTO DOCTOR (NAME, SPECIALIZATION)
VALUES ('Dr. Suresh Sharma','Orthopedics');

INSERT INTO DOCTOR (NAME, SPECIALIZATION)
VALUES ('Dr. Priya Verma','Pediatrics');

INSERT INTO DOCTOR (NAME, SPECIALIZATION)
VALUES ('Dr. Amit Singh','Dermatology');

INSERT INTO DOCTOR (NAME, SPECIALIZATION)
VALUES ('Dr. Kavita Gupta','Gynecology');

INSERT INTO DOCTOR (NAME, SPECIALIZATION)
VALUES ('Dr. Rohit Jain','Oncology');

INSERT INTO DOCTOR (NAME, SPECIALIZATION)
VALUES ('Dr. Sneha Kapoor','Psychiatry');

INSERT INTO DOCTOR (NAME, SPECIALIZATION)
VALUES ('Dr. Arjun Mehta','General Medicine');

INSERT INTO DOCTOR (NAME, SPECIALIZATION)
VALUES ('Dr. Pooja Yadav','Endocrinology');



INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
VALUES (TO_TIMESTAMP('2024-03-25 10:00','YYYY-MM-DD HH24:MI'),'General Checkup',1,2);

INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
VALUES (TO_TIMESTAMP('2024-03-25 11:00','YYYY-MM-DD HH24:MI'),'Follow-up Consultation',2,2);

INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
VALUES (TO_TIMESTAMP('2024-03-25 12:00','YYYY-MM-DD HH24:MI'),'Cardiology Review',3,3);

INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
VALUES (TO_TIMESTAMP('2024-03-25 14:00','YYYY-MM-DD HH24:MI'),'Orthopedic Check',4,4);

INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
VALUES (TO_TIMESTAMP('2024-03-25 15:00','YYYY-MM-DD HH24:MI'),'Dermatology Consultation',5,5);

INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
VALUES (TO_TIMESTAMP('2024-03-26 09:30','YYYY-MM-DD HH24:MI'),'Pediatric Visit',6,6);

INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
VALUES (TO_TIMESTAMP('2024-03-26 10:30','YYYY-MM-DD HH24:MI'),'Psychiatry Session',7,7);

INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
VALUES (TO_TIMESTAMP('2024-03-26 11:30','YYYY-MM-DD HH24:MI'),'Oncology Follow-up',8,8);

INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
VALUES (TO_TIMESTAMP('2024-03-26 13:00','YYYY-MM-DD HH24:MI'),'Endocrinology Consultation',9,9);

INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
VALUES (TO_TIMESTAMP('2024-03-26 14:00','YYYY-MM-DD HH24:MI'),'Gynecology Checkup',10,10);