-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('Satish Priyadarshi','Male', TO_DATE('1991-03-25','YYYY-MM-DD'),'satishpriyadarshi11@gmail.com','O_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('Amit Sharma','Male', TO_DATE('1990-01-15','YYYY-MM-DD'),'amit1@gmail.com','A_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('Neha Verma','Female', TO_DATE('1992-02-20','YYYY-MM-DD'),'neha2@gmail.com','B_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('Rahul Singh','Male', TO_DATE('1988-03-12','YYYY-MM-DD'),'rahul3@gmail.com','O_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('Priya Gupta','Female', TO_DATE('1995-04-25','YYYY-MM-DD'),'priya4@gmail.com','AB_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('Vikas Kumar','Male', TO_DATE('1991-05-30','YYYY-MM-DD'),'vikas5@gmail.com','A_NEGATIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('Sneha Kapoor','Female', TO_DATE('1993-06-10','YYYY-MM-DD'),'sneha6@gmail.com','B_NEGATIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('Arjun Mehta','Male', TO_DATE('1987-07-19','YYYY-MM-DD'),'arjun7@gmail.com','O_NEGATIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('Pooja Yadav','Female', TO_DATE('1994-08-23','YYYY-MM-DD'),'pooja8@gmail.com','AB_NEGATIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('Rohit Jain','Male', TO_DATE('1990-09-05','YYYY-MM-DD'),'rohit9@gmail.com','A_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('Kavita Mishra','Female', TO_DATE('1996-10-11','YYYY-MM-DD'),'kavita10@gmail.com','B_POSITIVE');
--
-- -- Users 11 through 100
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User11','Male', TO_DATE('1991-01-01','YYYY-MM-DD'),'user11@gmail.com','O_POSITIVE');
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User12','Female', TO_DATE('1992-02-02','YYYY-MM-DD'),'user12@gmail.com','A_POSITIVE');
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User13','Male', TO_DATE('1993-03-03','YYYY-MM-DD'),'user13@gmail.com','B_POSITIVE');
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User14','Female', TO_DATE('1994-04-04','YYYY-MM-DD'),'user14@gmail.com','AB_POSITIVE');
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User15','Male', TO_DATE('1995-05-05','YYYY-MM-DD'),'user15@gmail.com','O_NEGATIVE');
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User16','Female', TO_DATE('1996-06-06','YYYY-MM-DD'),'user16@gmail.com','A_NEGATIVE');
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User17','Male', TO_DATE('1997-07-07','YYYY-MM-DD'),'user17@gmail.com','B_NEGATIVE');
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User18','Female', TO_DATE('1998-08-08','YYYY-MM-DD'),'user18@gmail.com','AB_NEGATIVE');
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User19','Male', TO_DATE('1999-09-09','YYYY-MM-DD'),'user19@gmail.com','O_POSITIVE');
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User20','Female', TO_DATE('2000-10-10','YYYY-MM-DD'),'user20@gmail.com','A_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User21','Male', TO_DATE('1991-11-11','YYYY-MM-DD'),'user21@gmail.com','B_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User22','Female', TO_DATE('1992-12-12','YYYY-MM-DD'),'user22@gmail.com','AB_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User23','Male', TO_DATE('1993-01-13','YYYY-MM-DD'),'user23@gmail.com','O_NEGATIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User24','Female', TO_DATE('1994-02-14','YYYY-MM-DD'),'user24@gmail.com','A_NEGATIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User25','Male', TO_DATE('1995-03-15','YYYY-MM-DD'),'user25@gmail.com','B_NEGATIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User26','Female', TO_DATE('1996-04-16','YYYY-MM-DD'),'user26@gmail.com','AB_NEGATIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User27','Male', TO_DATE('1997-05-17','YYYY-MM-DD'),'user27@gmail.com','O_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User28','Female', TO_DATE('1998-06-18','YYYY-MM-DD'),'user28@gmail.com','A_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User29','Male', TO_DATE('1999-07-19','YYYY-MM-DD'),'user29@gmail.com','B_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User30','Female', TO_DATE('2000-08-20','YYYY-MM-DD'),'user30@gmail.com','AB_POSITIVE');
--
-- -- … continuing incrementally …
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User31','Male', TO_DATE('1991-09-21','YYYY-MM-DD'),'user31@gmail.com','O_NEGATIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User32','Female', TO_DATE('1992-10-22','YYYY-MM-DD'),'user32@gmail.com','A_NEGATIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User33','Male', TO_DATE('1993-11-23','YYYY-MM-DD'),'user33@gmail.com','B_NEGATIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User34','Female', TO_DATE('1994-12-24','YYYY-MM-DD'),'user34@gmail.com','AB_NEGATIVE');
--
-- -- … keep adding each user with the same pattern …
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User99','Male', TO_DATE('1999-05-30','YYYY-MM-DD'),'user99@gmail.com','O_POSITIVE');
--
-- INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP)
-- VALUES ('User100','Female', TO_DATE('2000-06-30','YYYY-MM-DD'),'user100@gmail.com','A_POSITIVE');
--
--
-- INSERT INTO DOCTOR (NAME, SPECIALIZATION)
-- VALUES ('Dr. Rajesh Kumar','Cardiology');
--
-- INSERT INTO DOCTOR (NAME, SPECIALIZATION)
-- VALUES ('Dr. Anjali Mehta','Neurology');
--
-- INSERT INTO DOCTOR (NAME, SPECIALIZATION)
-- VALUES ('Dr. Suresh Sharma','Orthopedics');
--
-- INSERT INTO DOCTOR (NAME, SPECIALIZATION)
-- VALUES ('Dr. Priya Verma','Pediatrics');
--
-- INSERT INTO DOCTOR (NAME, SPECIALIZATION)
-- VALUES ('Dr. Amit Singh','Dermatology');
--
-- INSERT INTO DOCTOR (NAME, SPECIALIZATION)
-- VALUES ('Dr. Kavita Gupta','Gynecology');
--
-- INSERT INTO DOCTOR (NAME, SPECIALIZATION)
-- VALUES ('Dr. Rohit Jain','Oncology');
--
-- INSERT INTO DOCTOR (NAME, SPECIALIZATION)
-- VALUES ('Dr. Sneha Kapoor','Psychiatry');
--
-- INSERT INTO DOCTOR (NAME, SPECIALIZATION)
-- VALUES ('Dr. Arjun Mehta','General Medicine');
--
-- INSERT INTO DOCTOR (NAME, SPECIALIZATION)
-- VALUES ('Dr. Pooja Yadav','Endocrinology');
--
--
--
-- INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
-- VALUES (TO_TIMESTAMP('2024-03-25 10:00','YYYY-MM-DD HH24:MI'),'General Checkup',1,2);
--
-- INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
-- VALUES (TO_TIMESTAMP('2024-03-25 11:00','YYYY-MM-DD HH24:MI'),'Follow-up Consultation',2,2);
--
-- INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
-- VALUES (TO_TIMESTAMP('2024-03-25 12:00','YYYY-MM-DD HH24:MI'),'Cardiology Review',3,3);
--
-- INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
-- VALUES (TO_TIMESTAMP('2024-03-25 14:00','YYYY-MM-DD HH24:MI'),'Orthopedic Check',4,4);
--
-- INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
-- VALUES (TO_TIMESTAMP('2024-03-25 15:00','YYYY-MM-DD HH24:MI'),'Dermatology Consultation',5,5);
--
-- INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
-- VALUES (TO_TIMESTAMP('2024-03-26 09:30','YYYY-MM-DD HH24:MI'),'Pediatric Visit',6,6);
--
-- INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
-- VALUES (TO_TIMESTAMP('2024-03-26 10:30','YYYY-MM-DD HH24:MI'),'Psychiatry Session',7,7);
--
-- INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
-- VALUES (TO_TIMESTAMP('2024-03-26 11:30','YYYY-MM-DD HH24:MI'),'Oncology Follow-up',8,8);
--
-- INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
-- VALUES (TO_TIMESTAMP('2024-03-26 13:00','YYYY-MM-DD HH24:MI'),'Endocrinology Consultation',9,9);
--
-- INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID)
-- VALUES (TO_TIMESTAMP('2024-03-26 14:00','YYYY-MM-DD HH24:MI'),'Gynecology Checkup',10,10);


INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User1','Male','1991-02-02','user1@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User2','Female','1992-03-03','user2@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User3','Male','1993-04-04','user3@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User4','Female','1994-05-05','user4@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User5','Male','1995-06-06','user5@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User6','Female','1996-07-07','user6@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User7','Male','1997-08-08','user7@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User8','Female','1998-09-09','user8@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User9','Male','1999-01-010','user9@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User10','Female','1990-02-011','user10@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User11','Male','1991-03-012','user11@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User12','Female','1992-04-013','user12@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User13','Male','1993-05-014','user13@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User14','Female','1994-06-015','user14@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User15','Male','1995-07-016','user15@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User16','Female','1996-08-017','user16@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User17','Male','1997-09-018','user17@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User18','Female','1998-01-019','user18@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User19','Male','1999-02-020','user19@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User20','Female','1990-03-021','user20@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User21','Male','1991-04-022','user21@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User22','Female','1992-05-023','user22@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User23','Male','1993-06-024','user23@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User24','Female','1994-07-025','user24@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User25','Male','1995-08-026','user25@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User26','Female','1996-09-027','user26@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User27','Male','1997-01-01','user27@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User28','Female','1998-02-02','user28@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User29','Male','1999-03-03','user29@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User30','Female','1990-04-04','user30@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User31','Male','1991-05-05','user31@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User32','Female','1992-06-06','user32@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User33','Male','1993-07-07','user33@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User34','Female','1994-08-08','user34@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User35','Male','1995-09-09','user35@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User36','Female','1996-01-010','user36@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User37','Male','1997-02-011','user37@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User38','Female','1998-03-012','user38@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User39','Male','1999-04-013','user39@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User40','Female','1990-05-014','user40@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User41','Male','1991-06-015','user41@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User42','Female','1992-07-016','user42@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User43','Male','1993-08-017','user43@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User44','Female','1994-09-018','user44@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User45','Male','1995-01-019','user45@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User46','Female','1996-02-020','user46@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User47','Male','1997-03-021','user47@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User48','Female','1998-04-022','user48@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User49','Male','1999-05-023','user49@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User50','Female','1990-06-024','user50@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User51','Male','1991-07-025','user51@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User52','Female','1992-08-026','user52@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User53','Male','1993-09-027','user53@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User54','Female','1994-01-01','user54@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User55','Male','1995-02-02','user55@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User56','Female','1996-03-03','user56@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User57','Male','1997-04-04','user57@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User58','Female','1998-05-05','user58@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User59','Male','1999-06-06','user59@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User60','Female','1990-07-07','user60@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User61','Male','1991-08-08','user61@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User62','Female','1992-09-09','user62@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User63','Male','1993-01-010','user63@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User64','Female','1994-02-011','user64@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User65','Male','1995-03-012','user65@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User66','Female','1996-04-013','user66@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User67','Male','1997-05-014','user67@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User68','Female','1998-06-015','user68@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User69','Male','1999-07-016','user69@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User70','Female','1990-08-017','user70@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User71','Male','1991-09-018','user71@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User72','Female','1992-01-019','user72@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User73','Male','1993-02-020','user73@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User74','Female','1994-03-021','user74@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User75','Male','1995-04-022','user75@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User76','Female','1996-05-023','user76@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User77','Male','1997-06-024','user77@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User78','Female','1998-07-025','user78@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User79','Male','1999-08-026','user79@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User80','Female','1990-09-027','user80@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User81','Male','1991-01-01','user81@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User82','Female','1992-02-02','user82@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User83','Male','1993-03-03','user83@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User84','Female','1994-04-04','user84@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User85','Male','1995-05-05','user85@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User86','Female','1996-06-06','user86@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User87','Male','1997-07-07','user87@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User88','Female','1998-08-08','user88@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User89','Male','1999-09-09','user89@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User90','Female','1990-01-010','user90@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User91','Male','1991-02-011','user91@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User92','Female','1992-03-012','user92@gmail.com','O_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User93','Male','1993-04-013','user93@gmail.com','A_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User94','Female','1994-05-014','user94@gmail.com','B_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User95','Male','1995-06-015','user95@gmail.com','AB_NEGATIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User96','Female','1996-07-016','user96@gmail.com','O_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User97','Male','1997-08-017','user97@gmail.com','A_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User98','Female','1998-09-018','user98@gmail.com','B_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User99','Male','1999-01-019','user99@gmail.com','AB_POSITIVE');
INSERT INTO PATIENT (NAME, GENDER, BIRTH_DATE, EMAIL, BLOOD_GROUP) VALUES ('User100','Female','1990-02-020','user100@gmail.com','O_NEGATIVE');

INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor1','Neurology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor2','Orthopedics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor3','Pediatrics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor4','Dermatology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor5','Gynecology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor6','Oncology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor7','Psychiatry');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor8','General Medicine');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor9','Endocrinology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor10','Cardiology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor11','Neurology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor12','Orthopedics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor13','Pediatrics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor14','Dermatology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor15','Gynecology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor16','Oncology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor17','Psychiatry');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor18','General Medicine');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor19','Endocrinology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor20','Cardiology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor21','Neurology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor22','Orthopedics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor23','Pediatrics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor24','Dermatology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor25','Gynecology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor26','Oncology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor27','Psychiatry');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor28','General Medicine');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor29','Endocrinology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor30','Cardiology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor31','Neurology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor32','Orthopedics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor33','Pediatrics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor34','Dermatology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor35','Gynecology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor36','Oncology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor37','Psychiatry');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor38','General Medicine');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor39','Endocrinology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor40','Cardiology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor41','Neurology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor42','Orthopedics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor43','Pediatrics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor44','Dermatology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor45','Gynecology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor46','Oncology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor47','Psychiatry');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor48','General Medicine');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor49','Endocrinology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor50','Cardiology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor51','Neurology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor52','Orthopedics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor53','Pediatrics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor54','Dermatology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor55','Gynecology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor56','Oncology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor57','Psychiatry');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor58','General Medicine');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor59','Endocrinology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor60','Cardiology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor61','Neurology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor62','Orthopedics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor63','Pediatrics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor64','Dermatology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor65','Gynecology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor66','Oncology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor67','Psychiatry');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor68','General Medicine');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor69','Endocrinology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor70','Cardiology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor71','Neurology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor72','Orthopedics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor73','Pediatrics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor74','Dermatology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor75','Gynecology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor76','Oncology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor77','Psychiatry');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor78','General Medicine');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor79','Endocrinology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor80','Cardiology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor81','Neurology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor82','Orthopedics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor83','Pediatrics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor84','Dermatology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor85','Gynecology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor86','Oncology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor87','Psychiatry');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor88','General Medicine');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor89','Endocrinology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor90','Cardiology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor91','Neurology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor92','Orthopedics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor93','Pediatrics');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor94','Dermatology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor95','Gynecology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor96','Oncology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor97','Psychiatry');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor98','General Medicine');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor99','Endocrinology');
INSERT INTO DOCTOR (NAME, SPECIALIZATION) VALUES ('Dr. Doctor100','Cardiology');

INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-02 10:00:00','Follow-up',1,1);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-03 11:00:00','Consultation',2,2);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-04 12:00:00','Review',3,3);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-05 13:00:00','Emergency',4,4);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-06 14:00:00','General Check',5,5);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-07 15:00:00','Dental',6,6);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-08 16:00:00','Skin Care',7,7);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-09 17:00:00','Heart Check',8,8);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-10 18:00:00','Eye Check',9,9);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-11 09:00:00','Checkup',10,10);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-12 10:00:00','Follow-up',11,11);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-13 11:00:00','Consultation',12,12);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-14 12:00:00','Review',13,13);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-15 13:00:00','Emergency',14,14);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-16 14:00:00','General Check',15,15);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-17 15:00:00','Dental',16,16);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-18 16:00:00','Skin Care',17,17);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-19 17:00:00','Heart Check',18,18);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-20 18:00:00','Eye Check',19,19);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-21 09:00:00','Checkup',20,20);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-22 10:00:00','Follow-up',21,21);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-23 11:00:00','Consultation',22,22);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-24 12:00:00','Review',23,23);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-25 13:00:00','Emergency',24,24);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-26 14:00:00','General Check',25,25);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-27 15:00:00','Dental',26,26);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-28 16:00:00','Skin Care',27,27);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-01 17:00:00','Heart Check',28,28);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-02 18:00:00','Eye Check',29,29);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-03 09:00:00','Checkup',30,30);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-04 10:00:00','Follow-up',31,31);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-05 11:00:00','Consultation',32,32);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-06 12:00:00','Review',33,33);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-07 13:00:00','Emergency',34,34);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-08 14:00:00','General Check',35,35);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-09 15:00:00','Dental',36,36);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-10 16:00:00','Skin Care',37,37);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-11 17:00:00','Heart Check',38,38);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-12 18:00:00','Eye Check',39,39);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-13 09:00:00','Checkup',40,40);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-14 10:00:00','Follow-up',41,41);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-15 11:00:00','Consultation',42,42);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-16 12:00:00','Review',43,43);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-17 13:00:00','Emergency',44,44);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-18 14:00:00','General Check',45,45);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-19 15:00:00','Dental',46,46);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-20 16:00:00','Skin Care',47,47);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-21 17:00:00','Heart Check',48,48);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-22 18:00:00','Eye Check',49,49);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-23 09:00:00','Checkup',50,50);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-24 10:00:00','Follow-up',51,51);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-25 11:00:00','Consultation',52,52);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-26 12:00:00','Review',53,53);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-27 13:00:00','Emergency',54,54);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-28 14:00:00','General Check',55,55);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-01 15:00:00','Dental',56,56);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-02 16:00:00','Skin Care',57,57);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-03 17:00:00','Heart Check',58,58);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-04 18:00:00','Eye Check',59,59);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-05 09:00:00','Checkup',60,60);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-06 10:00:00','Follow-up',61,61);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-07 11:00:00','Consultation',62,62);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-08 12:00:00','Review',63,63);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-09 13:00:00','Emergency',64,64);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-10 14:00:00','General Check',65,65);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-11 15:00:00','Dental',66,66);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-12 16:00:00','Skin Care',67,67);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-13 17:00:00','Heart Check',68,68);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-14 18:00:00','Eye Check',69,69);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-15 09:00:00','Checkup',70,70);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-16 10:00:00','Follow-up',71,71);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-17 11:00:00','Consultation',72,72);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-18 12:00:00','Review',73,73);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-19 13:00:00','Emergency',74,74);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-20 14:00:00','General Check',75,75);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-21 15:00:00','Dental',76,76);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-22 16:00:00','Skin Care',77,77);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-23 17:00:00','Heart Check',78,78);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-24 18:00:00','Eye Check',79,79);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-25 09:00:00','Checkup',80,80);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-26 10:00:00','Follow-up',81,81);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-27 11:00:00','Consultation',82,82);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-28 12:00:00','Review',83,83);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-01 13:00:00','Emergency',84,84);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-02 14:00:00','General Check',85,85);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-03 15:00:00','Dental',86,86);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-04 16:00:00','Skin Care',87,87);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-05 17:00:00','Heart Check',88,88);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-06 18:00:00','Eye Check',89,89);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-07 09:00:00','Checkup',90,90);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-08 10:00:00','Follow-up',91,91);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-09 11:00:00','Consultation',92,92);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-10 12:00:00','Review',93,93);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-11 13:00:00','Emergency',94,94);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-12 14:00:00','General Check',95,95);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-13 15:00:00','Dental',96,96);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-14 16:00:00','Skin Care',97,97);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-15 17:00:00','Heart Check',98,98);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-16 18:00:00','Eye Check',99,99);
INSERT INTO APPOINTMENT (APPOINTMENT_TIME, REASON, DOCTOR_ID, PATIENT_ID) VALUES ('2024-01-17 09:00:00','Checkup',100,100);
